#!/usr/bin/env sh
# NOTE:
#           | |        o
#       __, | |   __,
# |   | /  | |/ \_/  |  |
#  \_/|/\_/|_/\_/ \_/|_/|_/
#    /|
#    \|
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Config
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 6
yabai -m config auto_balance on
yabai -m config split_ratio 0.5
yabai -m config split_type auto
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config window_animation_duration 0.0
yabai -m config window_opacity_duration 0.0
yabai -m config window_origin_display default
yabai -m config window_shadow off
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config external_bar all:$(sketchybar --query bar | jq -r '.height'):0

# Setup spaces
 for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
 	yabai -m space --destroy 7
 done
 
 function setup_space {
     local idx="$1"
     local name="$2"
     local space=echo "setup space $idx : $name"
     space=$(yabai -m query --spaces --space "$idx")
     if [ -z "$space" ]; then
         yabai -m space --create
     fi
     yabai -m space "$idx" --label "$name"
 }
 
 setup_space 1 finder
 setup_space 2 wezterm
 setup_space 3 arc
 setup_space 4 obsidian
 setup_space 5 other

# Move some apps automatically to specific spaces
yabai -m rule --add app="^Finder$" space=1
yabai -m rule --add app="^Podcasts$" space=1
yabai -m rule --add app="WezTerm" space=2
yabai -m rule --add app="^Arc$" space=^3
yabai -m rule --add app="Obsidian" space=4

# No tiling
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="IINA" sticky=on manage=off
yabai -m rule --add app="Keka" manage=off
yabai -m rule --add app="Numi" sticky=on manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Shottr" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="VLC" sticky=on manage=off

yabai -m rule --apply

# JankyBorders - https://github.com/FelixKratz/JankyBorders 0xff7aa2f7
borders active_color="gradient(top_left=0xffcba6f7,bottom_right=0xffb4befe)" inactive_color="gradient(top_left=0xfff38ba8,bottom_right=0xffeba0ac)" width=4 2>/dev/null 1>&2 &

YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
