default:
    @just --list

build-menus:
    clang -std=c99 -Wall -Wextra -O2 \
        -framework ApplicationServices \
        -framework Carbon \
        menus/menus.c -o menus/menus
    codesign -s - menus/menus

build-trash:
    clang -Wall -Wextra -O2 \
        -framework CoreServices \
        trash/trash_monitor.c \
        -o trash/trash_monitor

build-stats:
    cargo build --manifest-path "$HOME"/.config/sketchybar/sketchybar-system-stats/Cargo.toml --release

clean:
    rm -f menus/menus
    rm -f trash/trash_monitor

build:
    just build-menus &
    just build-trash &
    just build-stats &
    wait
