default:
    @just --list

build-menus:
    clang -std=c99 -Wall -Wextra -O2 -F/System/Library/PrivateFrameworks/ -framework Carbon -framework SkyLight menus/menus.c -o menus/menus

build-trash:
    clang -Wall -Wextra -O2 -framework CoreServices trash/trash_monitor.c -o trash/trash_monitor

build-stats:
    cargo build --manifest-path "$HOME"/.config/sketchybar/sketchybar-system-stats/Cargo.toml --release

build: build-menus build-stats build-trash
