[package]
name = "stats_provider"
version = "0.4.0"
description = "A simple system stats event provider for Sketchybar."
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
sketchybar-rs = "0.2.0"
sysinfo = "0.31.2"
