"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" },
	{ run = 'nvim "%*"', block = true, desc = "nvim", for = "windows" }
]
reveal = [
	{ run = 'xdg-open "$(dirname "$0")"',            desc = "Reveal", for = "linux" },
	{ run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
	{ run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
	{ run = '''exiv2 "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
play = [
	{ run = 'iina --no-stdin "$@"', orphan = true, for = "macos" },
	{ run = 'vlc "%1"', orphan = true, for = "windows" },
	{ run = 'mpv "$@"', orphan = true, for = "linux" },
]

[plugin]
prepend_previewers = [
	{ name = "*.md", run = "glow" },
]
