[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" },
  { run = 'nvim "%*"', block = true, desc = "nvim", for = "windows" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$0")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiv2 "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
play = [
  { run = 'iina --no-stdin "$@"', orphan = true, for = "macos" },
  { run = 'vlc "%1"', orphan = true, for = "windows" },
  { run = 'mpv "$@"', orphan = true, for = "linux" },
]

[plugin]
prepend_previewers = [
  { url = "*.md", run = 'faster-piper --rely-on-preloader' },
  { url = "*.csv", run = 'faster-piper --rely-on-preloader' },
  { mime = "text/*", run = 'faster-piper --rely-on-preloader' },
  { url = "*/", run = 'faster-piper --rely-on-preloader' },
]
prepend_preloaders = [
  { url = "*.md", run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*.csv", run = 'faster-piper -- bat -p --color=always "$1"' },
  { mime = "text/*", run = 'faster-piper -- bat -p --color=always "$1"' },
  { url = "*/", run = 'faster-piper -- eza -TL=1 --icons=always --color=always --sort=extension "$1"' },
]
