"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" },
	{ run = 'nvim "%*"', block = true, desc = "nvim", for = "windows" }
]
open = [
	{ run = 'feh -Z "$@"', block = true, desc = "feh", for = "unix" }
]
play = [
	{ run = 'iina "$@"', orphan = true, for = "macos" },
	{ run = 'vlc "%1"', orphan = true, for = "windows" },
	{ run = 'mpv "$@"', orphan = true, for = "linux" },
]

[plugin]
prepend_previewers = [
	{ name = "*.md", run = "glow" },
]
