# NOTE:
#   _                  _
#  | |_  ___ _ __  ___| |__ _ _ _____ __ __
#  | ' \/ _ \ '  \/ -_) '_ \ '_/ -_) V  V /
#  |_||_\___/_|_|_\___|_.__/_| \___|\_/\_/

tap "felixkratz/formulae", trusted: {
  formulae: ["borders", "sketchybar", "svim"]
}
tap "homebrew-ffmpeg/ffmpeg", trusted: {
  formula: "ffmpeg"
}
tap "homebrew/bundle"
tap "homebrew/services"
tap "jundot/omlx", "https://github.com/jundot/omlx", trusted: {
  formula: "omlx"
}
tap "nikitabobko/tap", trusted: true
tap "osx-cross/avr", trusted: {
  formula: "avr-gcc@9"
}
tap "tw93/tap", trusted: true
brew "antidote"
brew "autoconf"
brew "avrdude"
brew "btop"
brew "cargo-instruments"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "dos2unix"
brew "exiv2"
brew "ffmpegthumbnailer"
brew "flac"
brew "git"
brew "hf"
brew "id3v2"
brew "imagemagick"
brew "make"
brew "mariadb"
brew "media-control"
brew "mole"
brew "nowplaying-cli"
brew "p7zip"
brew "pandoc"
brew "php"
brew "podman"
brew "podman-compose"
brew "poppler"
brew "rom-tools"
brew "switchaudio-osx"
brew "topgrade"
brew "ttyd"
brew "unar"
brew "unzip"
brew "viu"
brew "wget"
brew "zsh"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "felixkratz/formulae/svim"
brew "homebrew-ffmpeg/ffmpeg/ffmpeg", args: ["with-fdk-aac"]
brew "jundot/omlx/omlx"
brew "osx-cross/avr/avr-gcc@9"
cask "affinity"
cask "aerospace"
cask "betterdisplay"
cask "bruno"
cask "chatgpt"
cask "dbeaver-community"
cask "fluidvoice"
cask "font-fontawesome"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-liberation-nerd-font"
cask "font-maple-mono"
cask "font-roboto"
cask "font-source-sans-3"
cask "font-symbols-only-nerd-font"
cask "git-credential-manager"
cask "helium-browser"
cask "iina"
cask "linearmouse"
cask "localsend"
cask "macpacker"
cask "macshot"
cask "notunes"
cask "numi"
cask "qmk-toolbox"
cask "qlmarkdown"
cask "suspicious-package"
cask "wezterm@nightly"
cask "zed"
cask "zoom"
