after-startup-command = [
    'exec-and-forget open -n /Applications/WezTerm.app',
    'exec-and-forget open -n /Applications/Zen Browser.app',
    'exec-and-forget borders active_color="gradient(top_left=0xffcba6f7,bottom_right=0xffb4befe)" inactive_color="gradient(top_left=0xfff38ba8,bottom_right=0xffeba0ac)" width=4',
    'exec-and-forget sketchybar --reload',
]
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE PREVIOUS=$AEROSPACE_PREV_WORKSPACE'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       5
    outer.bottom =     5
    outer.top =        30
    outer.right =      5

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'

    alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
    alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
    alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    alt-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-f = 'fullscreen'
    alt-shift-f = 'macos-native-fullscreen'

    alt-shift-semicolon = [
        'exec-and-forget sketchybar --bar color=0x22f9e2af',
        'mode service'
    ]
    alt-shift-r = [
        'exec-and-forget sketchybar --bar color=0x22f38ba8',
        'mode resize'
    ]

[mode.service.binding]
    esc = [
        'reload-config',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    r = [
        'flatten-workspace-tree',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ] # reset layout
    f = [
        'layout floating tiling',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ] # Toggle between floating and tiling layout
    m = [
        'exec-and-forget $HOME/.config/sketchybar/menus/menus -tm',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    d = [
        'exec-and-forget $HOME/.config/sketchybar/menus/menus -td',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    backspace = [
        'close-all-windows-but-current',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]

    alt-shift-h = [
        'join-with left',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    alt-shift-j = [
        'join-with down',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    alt-shift-k = [
        'join-with up',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]
    alt-shift-l = [
        'join-with right',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]

    down = 'volume down'
    up = 'volume up'
    shift-down = [
        'volume set 0',
        'exec-and-forget sketchybar --bar color=0x00000000',
        'mode main',
    ]

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'balance-sizes'
    esc = [
    'exec-and-forget sketchybar --bar color=0x00000000',
    'mode main',
]

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 1 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 1 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.apple.podcasts'
run = 'move-node-to-workspace 2 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 3 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 3 --focus-follows-window'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 4 --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.raycast.macos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Preferences'
run = 'layout floating'
